### ISSUE TITLE
CRM: what's coming? when? what does that mean?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/MoFoLondon#19]
(Full Team Session or smaller breakouts people can attend?)
## Description:

What magical thing is a CRM and how might it impact work in the future? It will help to provide some examples of how Salesforce might influence our work and help us measure impact. We could invite Andrew from MoCo to provide a roadmap update / status / rollout plan. (Stephanie McVicker is our CRM liaison and can help plan)
### Time requirements:

30 mins?
### Space requirements:

probably 10 people per session if we repeat this one?
### Required attendees:

I think it can be voluntary -- people who are curious or want an update.

**Comment by shaghdoosti** [comment]
Had a chat to @valianttry this can be done virtually. Closing.
