### ISSUE TITLE
User Manuals: how to create them so we can work better together in our teams

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/MoFoLondon#23]
## Description:

If there's interest I can facilitate this for the whole org :)
See: https://docs.google.com/document/d/1W4_T8oiB5NMaOhhNV0-yNkTelu0c5uTkb2W3D-ts2-w/edit

**Comment by ldecoursy** [comment]
cc @OpenMatt

**Comment by OpenMatt** [comment]
@valianttry I love this idea. Can you say more about the specific kinds of documentation you're hoping to produce? What's the ideal MoFo customer or use case for this session?

**Comment by shaghdoosti** [comment]
Had a conversation with @valianttry -- this was an idea to keep in mind. Closing for now.
