### ISSUE TITLE
Working Open Workshop: Chicago planning

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/MoFoLondon#27]
### Time requirements:

60min
### Required attendees:

@arlissc @acabunoc

**Comment by ldecoursy** [comment]
This is not currently on the draft schedule. I think @kaythaney said it could be part of the time Science team has all together in the mornings

**Comment by ldecoursy** [comment]
@kaythaney Is that still ok with you? Or can you see where else this might fit with Science sched for the week? Let me know...

**Comment by kaythaney** [comment]
no worries! we can address in our H2 planning timeblock. :)

On Wed, Jun 1, 2016 at 9:59 AM, Lainie DeCoursy notifications@github.com
wrote:

> @kaythaney https://github.com/kaythaney Is that still ok with you? Or
> can you see where else this might fit with Science sched for the week? Let
> me know...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/MoFoLondon/issues/27#issuecomment-223000824,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAh17-8YuuuXTKVrVeHgLx2qPuZnqwzzks5qHZA4gaJpZM4IZIZu
> .

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by ldecoursy** [comment]
OK - closing this ticket. Thanks!
