### ISSUE TITLE
Internet of Things hub: drop-in maker clinic

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/MoFoLondon#39]
## Description:

Are you interested in learning & making away from keyboard? This zone will be kitted out with hardware, craft materials and other rapid prototyping tools to help you take your idea from post-it to reality. 

Bring a fresh idea hatched at the all-hands, or something you've been mulling over for a while, and we'll help you turn it into something physical that helps others understand, interact with and improve it.  

We'll also share reflections on prototyping practices we've been experimenting with and invite others to share their triumphs and challenges in these efforts as well. 
### Time requirements:

On-going with optional 15min. kickoff sessions each day.  
### Space requirements:

A corner with a small table, access to power, and ideally a place where we can store materials throughout the all-hands.
### Required attendees:

@thornet and @ileddigital
### Optional attendees:

Anyone interested in learning and making with physical prototypes and props.

**Comment by OpenMatt** [comment]
@thornet this is so awesome. Do you want MoCos to come too? If so, you can add it in Sched so that the rest of Mozilla knows this is happening.
http://mozillalondonallhands2016.sched.org/.

**Comment by thornet** [comment]
@OpenMatt thank you! yes, would love to open it up to all Mozillians. I'll add it to Sched. 

FYI, I'm talking with the Connected Devices team about possibly co-locating the clinic in their homeroom, as it could be a complement to their ideation sessions.

**Comment by ldecoursy** [comment]
@thornet Any update on whether we need to make space for this in our homeroom, or if you'll be located with Connected Devices (and do we know if they're in the same hotel)?

**Comment by thornet** [comment]
We're in the same hotel (thank the lord!), but awaiting confirmation. I
should know in a day or so.

On Fri, May 27, 2016 at 10:04 PM, Lainie DeCoursy notifications@github.com
wrote:

> @thornet https://github.com/thornet Any update on whether we need to
> make space for this in our homeroom, or if you'll be located with Connected
> Devices (and do we know if they're in the same hotel)?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/MoFoLondon/issues/39#issuecomment-222252729,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAtHZnrkLzuqsyGgmSyVSrLSk4GJNdREks5qF1xFgaJpZM4IiXsg
> .

## 

_Michelle Thorne_
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by ldecoursy** [comment]
@thornet The rooms will be locked at night, but if you have anything valuable it's suggested you store it in someone's hotel room. 

Also note that all MLN sessions will happen in the main MoFo space (that's 50-ish people huddled in smaller groups). Any update on whether or not this can be done in the Connected Devices space? I'm a little concerned if it needs to happen in our homeroom and we invite all MoCo it may get nutty in there.  cc @OpenMatt

**Comment by thornet** [comment]
Good news! This is confirmed for the CD homeroom. No need to worry about it in the MoFo space.
