### ISSUE TITLE
Strategic Plan: communications strategy

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/MoFoLondon#49]
## Description:

Discuss the internal / overall communications strategy for the Strategic Plan
### Time requirements:

60 - 90 mins
### Space requirements:

Informal
### Required attendees:

@KevZawacki @Lottarao @samanthaburton

**Comment by samanthaburton** [comment]
Hey @OpenMatt - @KevZawacki actually already logged this session [here](https://github.com/MozillaFoundation/MoFoLondon/issues/44).
