### ISSUE TITLE
Fellowship Contracting 

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/MoFoLondon#50]
## Description:

A time to talk about the how to implement certain stops laid out in the MOUs and Agreements -- e.g. if lobbying is involved in the fellowship work. Assuming Abigail Phillips will be joining us in London. This might be combined with the larger Fellowship meeting we already have scheduled.
### Time requirements:

1hr
### Space requirements:

4-6ppl
### Required attendees:

@vanessarhinesmith @kaythaney @auremoser Abigail Phillips (Lawyer)
### Dependencies: (Other sessions that need to happen before this one)

Abigail Phillips being in London.

**Comment by ldecoursy** [comment]
@Melechuga @kaythaney Can this happen as part of the Fellowships session on Wednesday? See #7 

Otherwise we'll need to find another day/time. Perhaps during electives on Wed or Thurs.

**Comment by kaythaney** [comment]
Let's put this as an agenda item for our Wednesday block of time for
Fellowships (1030-12 GMT). Big themes for that are unified fellowship
plans, shared/joint onboarding and process stuff (like this).

@melechuga - could you reach out to abigail (phillips) to see if she can
join for some of that time?

On Wed, Jun 1, 2016 at 10:19 AM, Lainie DeCoursy notifications@github.com
wrote:

> @Melechuga https://github.com/Melechuga @kaythaney
> https://github.com/kaythaney Can this happen as part of the Fellowships
> session on Wednesday? See #7
> https://github.com/MozillaFoundation/MoFoLondon/issues/7
> 
> Otherwise we'll need to find another day/time. Perhaps during electives on
> Wed or Thurs.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MozillaFoundation/MoFoLondon/issues/50#issuecomment-223007136,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAh17wnuCc5CItapd45hX8DzzCGo09Yzks5qHZUNgaJpZM4IozYv
> .

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by ldecoursy** [comment]
Once we're sure this is on your agenda for the Wed block, let's close this issue ;)
